django-ecommerce-app-main/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('products.urls')),   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-ecommerce-app-main/products/urls.py
from django.urls import path
from products import views

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:pk>/', views.product, name='product'),
    path('category/<int:pk>/', views.category_products, name='category_products'),
    path('search/', views.searched_products, name='search'),
    path('categories/', views.categories_all, name='categories_all'),
    path('cart/', views.cart, name='cart'),
    path('cart_action/<int:pk>/', views.cart_action, name='cart_action'),
    path('cart_quantity/<int:pk>/', views.cart_quantity, name='cart_quantity'),
    path('complete_order/', views.complete_order, name='complete_order'),
    path('opinion/<int:pk>/', views.opinion_action, name='opinion'),
    path('user_order/<int:pk>/', views.user_order, name='user_order'),
]

django-ecommerce-app-main/users/urls.py
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from users.forms import NewUserPasswordChangeForm, NewUserPasswordResetEmailForm, NewUserPasswordResetForm

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.profile_user, name='profile'),
    path('logout/', views.logout_user, name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='password_change.html', form_class=NewUserPasswordChangeForm, success_url = '/'), name='password_change'), 
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html', form_class=NewUserPasswordResetEmailForm), name='password_reset'), 
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),      
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', form_class=NewUserPasswordResetForm), name='password_reset_confirm'), 
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),      
]

django-ecommerce-app-main/products/models.py
from django.db import models
from django.utils import timezone
from products.storage import OverriteFile

class Category(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.name)
    
def get_image_filepath(self, filename):
    return f'./products/{self.name}_{self.created_date_time}.png'

def get_default_image():
    return f'./products/default.png'  

class Product(models.Model):
    category = models.ForeignKey("products.Category", on_delete=models.CASCADE, related_name='product_category', blank=False, null=False)
    name = models.CharField(max_length=255, blank=False, null=False)
    image = models.ImageField(upload_to=get_image_filepath, default=get_default_image, storage=OverriteFile(), blank=False, null=False)
    description = models.CharField(max_length=1024, blank=True, null=True)
    price = models.FloatField(max_length=64, blank=False, null=False)
    is_recommended = models.BooleanField(default=True)
    created_date_time = models.DateTimeField(default=timezone.now, blank=False, null=False)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return str(self.name)
    
class Order(models.Model):
    
    DELIVERY_METHODS = [
        ((1, 'Courier delivery')),
        ((2, 'Pickup at a parcel locker')),
        ((3, 'Personal pickup')),     
    ]
    
    PAYMENT_METHODS = [
        ((1, 'Cash/card payment on delivery')),
        ((2, 'Online payment by credit card')),
        ((3, 'Traditional money transfer')),
    ]

    user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name='order_user', blank=True, null=True)
    first_name_order = models.CharField(max_length=255, blank=False, null=False)
    last_name_order = models.CharField(max_length=255, blank=False, null=False)
    delivery_method_order = models.IntegerField(choices=DELIVERY_METHODS, default=1, blank=False, null=False)
    payment_method_order = models.IntegerField(choices=PAYMENT_METHODS, default=1, blank=False, null=False)
    country_order = models.CharField(max_length=255, blank=False, null=False)
    city_order = models.CharField(max_length=255, blank=False, null=False)
    street_order = models.CharField(max_length=255, blank=False, null=False)
    house_number_order = models.CharField(max_length=255, blank=False, null=False)
    zip_code_order = models.CharField(max_length=255, blank=False, null=False)
    phone_number_order = models.CharField(max_length=255, blank=False, null=False)
    email_order = models.EmailField(max_length=255, blank=False, null=False)
    date_time_order = models.DateTimeField(default=timezone.now, blank=False, null=False)
     
    def __str__(self):
        return str(self.id) 

class OrderProduct(models.Model):
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name='orderproduct_product', blank=False, null=False)
    quantity = models.FloatField(default=1.0, blank=False, null=False)
    order_id = models.ForeignKey("products.Order", on_delete=models.CASCADE, related_name='orderproduct_order_id', blank=True, null=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    
    def __str__(self):
        return str(self.id)
    
class Opinion(models.Model):
    product =  models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name='opinion_product', blank=False, null=False)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE, related_name='opinion_user', blank=False, null=False)
    rating = models.CharField(max_length=1, blank=False, null=False, default='5')
    content = models.CharField(max_length=1024, blank=True, null=True)
    created_date_time = models.DateTimeField(default=timezone.now, blank=False, null=False)

    class Meta:
        unique_together = ('product', 'user')


    def __str__(self):
        return str(self.id)

django-ecommerce-app-main/products/forms.py
from django import forms
from django.forms import ModelForm
from products.models import Order

class OrderForm(ModelForm):
    country_order = forms.CharField(label='Country', widget=forms.TextInput(attrs={'class': 'form-control'}))
    city_order = forms.CharField(label='City', widget=forms.TextInput(attrs={'class': 'form-control'}))
    street_order = forms.CharField(label='Street', widget=forms.TextInput(attrs={'class': 'form-control'}))
    house_number_order = forms.CharField(label='House number', widget=forms.TextInput(attrs={'class': 'form-control'}))
    zip_code_order = forms.CharField(label='Zip code', widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name_order = forms.CharField(label='First name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name_order = forms.CharField(label='Last name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email_order = forms.CharField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number_order = forms.CharField(label='Phone number', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Order
        fields = ('country_order', 'city_order', 'street_order', 'house_number_order', 'zip_code_order','first_name_order', 'last_name_order', 'email_order', 'phone_number_order',)

django-ecommerce-app-main/products/views.py
from django.shortcuts import render, redirect
from products.models import Product, Category, OrderProduct, Order, Opinion
from django.db.models import Sum, F, Count, Avg
from products.forms import OrderForm
from django.core.paginator import Paginator
from django.core.mail import EmailMessage

def home(request):
    products = Product.objects.filter(is_visible=True, is_recommended=True).order_by('-id')
    context = {'products': products}
    return render(request, 'home.html', context=context)

def product(request, pk):
    product = Product.objects.get(pk=pk)
    opinions = Opinion.objects.filter(product=pk).order_by('-created_date_time')
    opinions_query = Opinion.objects.filter(product=pk).aggregate(Sum('rating'), Count('id'), Avg('rating'))
    opinions_rating = opinions_query['rating__sum']
    opinions_count = opinions_query['id__count']
    opinions_average_rating = opinions_query['rating__avg'] if opinions_count is not None and opinions_rating is not None else 0
    user_opinion = None

    if request.user.is_authenticated:
        try:
            user_opinion = Opinion.objects.get(user=request.user, product=pk)
        except Opinion.DoesNotExist:
            pass

    context = {
        'product': product,
        'opinions': opinions,
        'opinions_count': opinions_count,
        'opinions_rating': opinions_rating,
        'opinions_average_rating': opinions_average_rating,
        'user_opinion': user_opinion}
    
    return render(request, 'product.html', context=context)

def category_products(request, pk):
    products = Product.objects.filter(is_visible=True, category=pk).order_by('id')
    category = Category.objects.get(pk=pk)
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {'page': page, 'category': category}
    return render(request, 'category_products.html', context=context)

def searched_products(request):
    products = Product.objects.filter(is_visible=True, name__contains=request.POST['searched']).order_by('id')
    return render(request, 'searched_products.html', context={'products': products})

def categories_all(request):
    return render(request, 'categories_all.html')

def cart(request):
    initial_data = {}
    pk_cookie, products, cart_total = None, None, None    
    cookie = request.COOKIES.get('cart') or None

    if request.user.is_authenticated:
        initial_data = {
            'country_order': request.user.country,
            'city_order': request.user.city,    
            'street_order': request.user.street,
            'house_number_order': request.user.house_number, 
            'zip_code_order': request.user.zip_code, 
            'first_name_order': request.user.first_name,
            'last_name_order': request.user.last_name,    
            'email_order': request.user.email,
            'phone_number_order': request.user.phone_number,         
        }
        
    if cookie:
        pk_cookie = [int(pk_order_product) for pk_order_product in cookie.split('_')]
        products = OrderProduct.objects.filter(pk__in=pk_cookie) 
        cart_total = OrderProduct.objects.filter(pk__in=pk_cookie).annotate(orderproduct_total=F('product__price') * F('quantity')).aggregate(total=Sum('orderproduct_total'))['total']

    context = {'products': products, 
               'cart_total': cart_total, 
               'form': OrderForm(initial=initial_data)} 
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.user = request.user if request.user.is_authenticated else None
            order.delivery_method_order = request.POST['delivery_method_order']
            order.payment_method_order = request.POST['payment_method_order']
            OrderProduct.objects.filter(pk__in=pk_cookie).update(order_id=order.pk)
            order.save()
            response = redirect('complete_order')
            response.delete_cookie('cart')
            email = EmailMessage('Your order is ready', f'Your order has been assigned a number #{order.pk}', to=[order.email_order])
            email.send()
            return response
    return render(request, 'cart.html', context=context)     

def cart_action(request, pk):
    response = redirect('cart')
    action = request.GET.get('action')
    cookie = request.COOKIES.get('cart') or None
    if action == 'add':
        product = Product.objects.get(pk=pk)
        if cookie:
            pk_cookie = [int(pk_order_product) for pk_order_product in cookie.split('_')]
            order_products = OrderProduct.objects.filter(pk__in=pk_cookie)
            found = any(item.product.pk==pk for item in order_products)
            if found:
                order_product = OrderProduct.objects.get(pk__in=pk_cookie, product=product)
                order_product.quantity += 1
                order_product.save() 
            else:
                new_product = OrderProduct.objects.create(product=product)
                response.set_cookie(key='cart', value=f'{cookie}_{new_product.pk}')
        else:
            new_product = OrderProduct.objects.create(product=product)
            response.set_cookie(key='cart', value=f'{new_product.pk}')
        return response

    elif action == 'remove':
        pk_cookie = [int(pk_order_product) for pk_order_product in cookie.split('_')]
        pk_cookie.remove(pk)
        if len(pk_cookie) > 0 :
            response.set_cookie(key='cart', value="_".join(map(str, pk_cookie)))
        else:
            response.delete_cookie('cart')
        order_product = OrderProduct.objects.get(pk=pk)
        order_product.delete()
    return response

def cart_quantity(request, pk):
    response = redirect('cart')
    order_product = OrderProduct.objects.get(pk=pk) 
    action = request.GET.get('action')
    if action == 'add':
        order_product.quantity += 1 

    elif action == 'remove':
        order_product.quantity -= 1

    if order_product.quantity == 0:
        cookie = request.COOKIES.get('cart') or None
        pk_cookie = [int(pk_order_product) for pk_order_product in cookie.split('_')]
        pk_cookie.remove(pk)

        if len(pk_cookie) > 0 :
            response.set_cookie(key='cart', value="_".join(map(str, pk_cookie)))
        else:
            response.delete_cookie('cart')
        order_product.delete()
    else:
        order_product.save()

    return response

def complete_order(request):
    return render(request, 'complete_order.html')

def opinion_action(request, pk):
    if request.user.is_authenticated:
        action = request.GET.get('action')
        if action == 'add':
            product = Product.objects.get(pk=pk)
            Opinion.objects.create(user=request.user, product=product, rating=request.POST['rating'], content=request.POST['content'])
        elif action == 'remove':
            opinion = Opinion.objects.get(user=request.user, product=pk)
            opinion.delete()
        return redirect('product', pk=pk)

def user_order(request, pk):
    order = Order.objects.get(pk=pk)
    if order.user == request.user:
            order_products = OrderProduct.objects.filter(order_id=order)
            cart_total = OrderProduct.objects.filter(order_id=order).annotate(orderproduct_total=F('product__price') * F('quantity')).aggregate(total=Sum('orderproduct_total'))['total']
            context = {
                'order': order,
                'order_products': order_products,
                'cart_total': cart_total
            }
            return render(request, 'user_order.html', context=context)
    else:
        return redirect('home')

django-ecommerce-app-main/products/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Ecommerce App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container flex-column">

            <div class="col-12 d-flex justify-content-center align-items-center">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="navbar-brand" href="{% url 'home' %}">Ecommerce App</a>
                    </li>
                    <li>
                        <form method="POST" action="{% url 'search' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="input-group">
                                <input name="searched" type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-append">
                                    <button class="btn btn-outline-primary">Search</button>
                                </span>
                        
                            </div>
                        </form>
                    </li>
                    <li class="navbar-item">
                        <div class="dropdown">
                            <a class="btn dropdown-toggle nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Contact</a>
                            <ul class="dropdown-menu dropdown-menu-dark">
                              <li><a class="dropdown-item" href="#">Email: example@example.com</a></li>
                              <li><a class="dropdown-item" href="#">Phone number: 123456789</a></li>
                            </ul>
                          </div>
                    </li>
                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="navbar-item">
                        <a class="nav-link" href="{% url 'cart' %}">Cart</a>
                    </li>
                </ul>
            </div>

            <ul class="navbar-nav">
                {% for item in categories|slice:":6" %}
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'category_products' item.pk %}">{{ item.name }}</a>
                </li>
                {% endfor %}
                <li class="navbar-item">
                    <a class="nav-link" href="{% url 'categories_all' %}">All</a>
                </li>
            </ul>

        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
</body>
</html>

django-ecommerce-app-main/products/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>Cart</h4>
    <hr class="hr" />

    {% if products %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th class="col">Product</th>
                <th class="col">Price</th>
                <th class="col">Quantity</th>
                <th class="col">Total</th>
                <th class="col">Operation</th>
            </tr>
        </thead>
        <tbody>
            {% for item in products %}
            <tr>
                <td>
                    <a class="text-decoration-none text-primary" href="{% url 'product' item.product.pk %}">{{ item.product.name }}</a>
                </td>
                <td>${{ item.product.price }}</td>
                <td>
                    <span class="input-group-btn">
                    <a class="text-decoration-none btn btn-sm btn-outline-danger" href="{% url 'cart_quantity' item.pk %}?action=remove">-</a>
                    </span>
                    <span type="text" id="quantity" name="quantity">{{ item.quantity }}</span>
                    <span class="input-group-btn">
                        <a class="text-decoration-none btn btn-sm btn-outline-success" href="{% url 'cart_quantity' item.pk %}?action=add">+</a>
                    </span>     
                    </td>
                <td>${{ item.get_total }}</td>
                <td><a class="text-decoration-none text-danger" href="{% url 'cart_action' item.pk %}?action=remove">Remove</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <form method="POST" action="{% url 'cart' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="card my-2">
        <div class="card-body">
            <h4>Delivery method:</h4>
            <hr class="hr" />
            <select name="delivery_method_order" class="form-select">
                <option value="1" selected>Courier delivery</option>
                <option value="2">Pickup at a parcel locker</option>
                <option value="3">Personal pickup</option>
            </select>
        </div>
    </div>

    <div class="card my-2">
        <div class="card-body">
            <h4>Paymnet method:</h4>
            <hr class="hr" />
            <select name="payment_method_order" class="form-select">
                <option value="1" selected>Cash/card payment on delivery</option>
                <option value="2">Online payment by credit card</option>
                <option value="3">Traditional money transfer</option>
            </select>
        </div>
    </div>

    <div class="card my-2">
        <div class="card-body">
            <h4>Shipping information:</h4>
            <hr class="hr" />
            {{ form.as_p }}
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
              <p>Total: ${{ cart_total|floatformat:2 }}</p> 
              <button class="btn btn-outline-success">Submit</button> 
        </div>
    </div>

    </form>
    {% else %}
    <span>Cart is empty.</span>
    {% endif %}  
</div>
{% endblock %}

django-ecommerce-app-main/products/templates/categories_all.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>All categoires</h4>
    <hr class="hr" />
    {% for item in categories %}
    <a class="btn btn-outline-primary my-1" href="{% url 'category_products' item.pk %}">{{ item.name }}</a>
    {% empty %}
    <span>Add at least one category in the database using the administration panel.</span>
    {% endfor %}
</div>
{% endblock %}

django-ecommerce-app-main/products/templates/category_products.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>{{ category }}</h4>
    <hr class="hr" />
    <div class="row card-group">
        {% for item in page %}
        <div class="col-3 my-3">
            <div class="card h-100">
                <img src="{{ item.image.url }}" alt="image" class="card-img-top" style="height: 200px;">
                <div class="card-body">
                    <ul class="list-inline">
                        <li>
                            <a class="card-title text-decoration-none">{{ item.name }}</a>
                        </li>
                        <li><small class="text-muted">{{ item.category }}</small></li>
                    </ul>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <div>
                        <a class="btn btn-sm btn-outline-primary" href="{% url 'cart_action' item.pk %}?action=add">Add to cart</a>
                        <a class="btn btn-sm btn-outline-success" href="{% url 'product' item.pk %}">View</a>
                    </div>
                    <div class="text-right">
                        <p class="text-primary">${{ item.price }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <span>There is no product assigned to this category.</span>
        {% endfor %}  
    </div>

    {% if page %}
    <nav aria-label="pagination">
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
            {% endif %} 

            <li class="page-item"><a class="page-link" href="#">page {{ page.number }} of {{ page.paginator.num_pages}}</a></li>

            {% if page.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">Last</a></li>
            {% endif %} 
        </ul>
    </nav>
    {% endif %}

</div>
{% endblock %}

django-ecommerce-app-main/products/templates/complete_order.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>Success</h4>
    <p>Your order has been shipped.</p>
</div>
{% endblock %}

django-ecommerce-app-main/products/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>We recommend</h4>
    <hr class="hr" />
    <div class="row card-group">
        {% for item in products %}
        <div class="col-3 my-3">
            <div class="card h-100">            
                <img src="{{ item.image.url }}" alt="image" class="card-img-top" style="height: 200px;">
                <div class="card-body">
                    <ul class="list-inline">
                        <li><a class="card-title text-decoration-none">{{ item.name }}</a></li>
                        <li><small class="text-muted">{{ item.category }}</small></li>
                    </ul>
                </div>
                
                <div class="card-footer d-flex justify-content-between">
                    <div>
                        <a class="btn btn-sm btn-outline-primary" href="{% url 'cart_action' item.pk %}?action=add">Add to cart</a>
                        <a class="btn btn-sm btn-outline-success" href="{% url 'product' item.pk %}">View</a>
                    </div>
                    <div class="text-right">
                        <p class="text-primary">${{ item.price }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <span>Add a product using the admin panel and check is_recommended = True to make it appear here.</span>
        {% endfor %}
    </div>
</div>
{% endblock %}

django-ecommerce-app-main/products/templates/searched_products.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>Searched products</h4>
    <hr class="hr" />
    <div class="row card-group">
        {% for item in products %}
        <div class="col-3 my-3">
            <div class="card h-100">
                <img src="{{ item.image.url }}" alt="image" class="card-img-top" style="height: 200px;">
                <div class="card-body">
                    <ul class="list-inline">
                        <li>
                            <a class="card-title text-decoration-none">{{ item.name }}</a>
                        </li>
                        <li><small class="text-muted">{{ item.category }}</small></li>
                    </ul>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <div>
                        <a class="btn btn-sm btn-outline-primary" href="{% url 'cart_action' item.pk %}?action=add">Add to cart</a>
                        <a class="btn btn-sm btn-outline-success" href="{% url 'product' item.pk %}">View</a>
                    </div>
                    <div class="text-right">
                        <p class="text-primary">${{ item.price }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <span>No product found.</span>
        {% endfor %}
    </div>
</div>
{% endblock %}

django-ecommerce-app-main/products/templates/user_order.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-3 min-vh-100">
    <h4>Order number: #{{ order.pk }}</h4>
    <hr class="hr" />
    <div class="card">
        <div class="card-body">
            <ul class="list-inline">
              <p>Date/time: {{ order.date_time_order }}</p>
              <p>Delivery method: {{ order.get_delivery_method_order_display }}</p>
              <p>Payment method: {{ order.get_payment_method_order_display }}</p>
              <p>Delivery address: {{ order.country_order }}, {{ order.city_order }}, {{  order.street_order }} {{  order.house_number_order }}, {{  order.zip_code_order }}</p>
              <p>Ordering person: {{ order.first_name_order }} {{ order.last_name_order }}, {{ order.email_order }}, {{ order.phone_number_order }}</p>
            </ul>
        </div>
    </div>
    <table class="table table-bordered my-3">
        <thead>
            <tr>
                <th class="col">Product</th>
                <th class="col">Price</th>
                <th class="col">Quantity</th>
                <th class="col">Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order_products %}
            <tr>
                <td>
                    <a class="text-decoration-none text-primary" href="{% url 'product' item.product.pk %}">{{ item.product.name }}</a>
                </td>
                <td>${{ item.product.price }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.get_total }}</td>
              
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="card my-3">
        <div class="card-body">
              <span>Total: ${{ cart_total|floatformat:2 }}</span> 
        </div>
    </div>

    <a class="btn btn-outline-primary" href="{% url 'profile' %}">Back</a>

</div>
{% endblock %}